# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "taskmapper-lighthouse"
  s.version = "0.10.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hong"]
  s.date = "2013-04-16"
  s.description = "Allows taskmapper to interact with Lighthouse's issue tracking system."
  s.email = "hong.quach@abigfisch.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/provider/comment.rb",
    "lib/provider/lighthouse.rb",
    "lib/provider/project.rb",
    "lib/provider/ticket.rb",
    "lib/taskmapper-lighthouse.rb",
    "spec/comments_spec.rb",
    "spec/fixtures/projects.json",
    "spec/fixtures/projects/54448.json",
    "spec/fixtures/projects/54448.xml",
    "spec/fixtures/projects/create.json",
    "spec/fixtures/projects/create.xml",
    "spec/fixtures/tickets.json",
    "spec/fixtures/tickets/2.json",
    "spec/fixtures/tickets/2.xml",
    "spec/fixtures/tickets/5.json",
    "spec/fixtures/tickets/5.xml",
    "spec/fixtures/tickets/create.json",
    "spec/fixtures/tickets/create.xml",
    "spec/projects_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/taskmapper-lighthouse_spec.rb",
    "spec/tickets_spec.rb",
    "taskmapper-lighthouse.gemspec"
  ]
  s.homepage = "http://github.com/kiafaldorius/taskmapper-lighthouse"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "TaskMapper Provider for Lighthouse"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<taskmapper>, [">= 0"])
      s.add_runtime_dependency(%q<xml-simple>, ["~> 1.1"])
      s.add_runtime_dependency(%q<addressable>, ["~> 2.2"])
      s.add_runtime_dependency(%q<lighthouse-api>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_development_dependency(%q<rcov>, ["~> 1.0"])
    else
      s.add_dependency(%q<taskmapper>, [">= 0"])
      s.add_dependency(%q<xml-simple>, ["~> 1.1"])
      s.add_dependency(%q<addressable>, ["~> 2.2"])
      s.add_dependency(%q<lighthouse-api>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.8"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_dependency(%q<rcov>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<taskmapper>, [">= 0"])
    s.add_dependency(%q<xml-simple>, ["~> 1.1"])
    s.add_dependency(%q<addressable>, ["~> 2.2"])
    s.add_dependency(%q<lighthouse-api>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.8"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
    s.add_dependency(%q<simplecov>, ["~> 0.5"])
    s.add_dependency(%q<rcov>, ["~> 1.0"])
  end
end

